Fix broken wireshark build workflow on macOS
### Motivation

See https://github.com/apache/pulsar-client-cpp/actions/runs/8276076995/job/22644077705

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
```

`brew install` failed because the wireshark dependency depends on
python@3.12 and it failed at `brew link`.

### Modifications

Remove the existing binaries that might conflict.