[python] Made the script for building Docker images for Python work (#8153)
### Motivation

Currently, enabling SNAPPY compression on the Python client causes a segmentation fault. I think this is because the Docker images for building the Python clients uploaded to Docker Hub do not include the SNAPPY library.

We need to run `pulsar-client-cpp/docker/create-images.sh` in order to build the latest Docker images that include the SNAPPY library, but this script fails for two reasons:

1. Log4cxx compilation fails. Currently the source of log4cxx is from the master branch, but if we get the source of tag `v0.11.0` and compile it, it will succeed.
```
In file included from logstream.cpp:24:0:
../../../src/main/include/log4cxx/private/log4cxx_private.h:43:31: error: token "@" is not valid in preprocessor expressions
 #define LOG4CXX_INIT_IOS_BASE @INIT_IOS_BASE@
                               ^
logstream.cpp:38:5: note: in expansion of macro ‘LOG4CXX_INIT_IOS_BASE’
 #if LOG4CXX_INIT_IOS_BASE
     ^
```
2. Building the image `pulsar-build/manylinux-cp34-cp34m` fails. This is probably because Python 3.4 has already reached EOL in 2014 and is no longer included in the base image `quay.io/pypa/manylinux1_x86_64`.
```
Step 8/32 : RUN ln -s /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}m /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}
 ---> Running in 0e1d652c2c29
ln: creating symbolic link `/opt/python/cp34-cp34m/include/python3.4' to `/opt/python/cp34-cp34m/include/python3.4m': No such file or directory
The command '/bin/sh -c ln -s /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}m /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}' returned a non-zero code: 1
```

### Modifications

1. Get the source of Log4cxx from tag v0.11.0 when building the Docker images.
2. Do not build the Docker image for Python 3.4.